### ISSUE TITLE
commons directory does not respect --data arg

### ISSUE THREAD

**Issue by jmeowmeow** [fedwiki/wiki-plugin-image#7]
When we start wiki with:

` wiki --data /home/wiki/.wiki2`

the "commons" property at launch does not respect the --data the way other directory paths do.

friends starting
[
  {
    _: [],
    data: '/home/wiki/.wiki2/jeff.pixiereport.com',
    d: '/home/wiki/.wiki2',
    f: true,
    farm: true,
    security_type: 'wiki-security-friends',
    cookieSecret: 'something secret',
    session_duration: 365,
    valueOf: undefined,
    port: 3000,
    root: '/usr/local/lib/node_modules/wiki/node_modules/wiki-server',
    home: 'welcome-visitors',
    commons: '/home/wiki/.wiki/commons',
    packageDir: '/usr/local/lib/node_modules/wiki/node_modules',
    url: 'http://jeff.pixiereport.com',
    client: '/usr/local/lib/node_modules/wiki/node_modules/wiki-client/client',
    db: '/home/wiki/.wiki2/jeff.pixiereport.com/pages',
    status: '/home/wiki/.wiki2/jeff.pixiereport.com/status',
    assets: '/home/wiki/.wiki2/jeff.pixiereport.com/assets',
    recycler: '/home/wiki/.wiki2/jeff.pixiereport.com/recycle',
    id: '/home/wiki/.wiki2/jeff.pixiereport.com/status/owner.json',
    uploadLimit: '5mb',
    secure_cookie: false,
    neighbors: '',
    debug: true,
    database: { type: './page' },
    security_legacy: false
  }

**Comment by paul90** [comment]
This will be fixed by fedwiki/wiki#141

Until that fix is available, you can set the location of the commons with `--commons /home/wiki/.wiki2/commons`.
